FROM node:8.12.0-alpine

#SET UP OUR DIRECTORY STRUCTURE
ENV API_DIR /api
RUN mkdir $API_DIR
WORKDIR $API_DIR

#COPY OUR FILE AND INSTALL
COPY . $API_DIR
RUN npm install

#SET A DEFAULT COMMAND
CMD npm start
